options:
  aws-public-key:
    type: string
    default: ""
    description: Amazon Public Key for S3
  aws-secret-key:
    type: string
    default: ""
    description: Amazon Secret Key for S3
  s3-bucket:
    type: string
    default: ""
    description: Amazon S3 Bucket
  flush-opcode-cache:
    type: boolean
    default: False
    description: When set to True will flush the OpCode Cache
  flush-wp-cache:
    type: boolean
    default: False
    description: When set to True will flush the WordPress SuperCache and LegacyCache
