options:
  tuning:
    type: string
    default: "single"
    description: | 
      This is the tuning level for the WordPress setup. There are three options: bare, single, and optimized.
      Bare will give you a nearly un-altered WordPress setup, as if you'd downloaded and set it up yourself.
      Single will provide you with everything you need to run a singlular unit of WordPress. This doesn't take in to 
        consideration that you'll be scaling at all. However, it will allow you to use WordPress free of any troubles and pesky 
        limitations that typically happen during "optimized". While you _can_ scale out with this setting I encourage you read the README
      Optimized will give you a hardened WordPress setup. Some of the features in the Admin panel will be locked down and theme edits/plugins
        can only be updated through he charm. This is the recommended setup for those who are in serious need of constant scaling.
