options:
  enable-plugins:
    type: string
    default: "false"
    description: In scale-out environments you typically don't want people to update plugins directly. This will only cause issues with other units.
